---
# tasks file for vault
- name: "show a vault secret"
  debug:
    msg: "{{ secret | json_query(query_1) }}"
    #var:
    #verbosity:
- name: "show a vault secret"
  debug:
    msg: "{{ secret | json_query(query_2) }}"
    #var:
